# This file is used to generate the `generated.rs` file with userdata accessors.

[accessors.single_strings]
"album"                   = "©alb"
"copyright"               = "cprt"
"encoder"                 = "©too"
"lyrics"                  = "©lyr"
"movement"                = "©mvn"
"publisher"               = "©pub"
"title"                   = "©nam"
"tv_episode_name"         = "tven"
"tv_network_name"         = "tvnn"
"tv_show_name"            = "tvsh"
"work"                    = "©wrk"
"year"                    = "©day"
"isrc"                    = "----:com.apple.iTunes:ISRC"
"label"                   = "----:com.apple.iTunes:LABEL"
"album_sort_order"        = "soal"
"title_sort_order"        = "sonm"
"tv_show_name_sort_order" = "sosn"


[accessors.multiple_strings]
"album_artist"            = "aART"
"artist"                  = "©ART"
"category"                = "catg"
"comment"                 = "©cmt"
"composer"                = "©wrt"
"custom_genre"            = "©gen"
"description"             = "desc"
"grouping"                = "©grp"
"keyword"                 = "keyw"
"lyricist"                = "----:com.apple.iTunes:LYRICIST"
"album_artist_sort_order" = "soaa"
"artist_sort_order"       = "soar"
"composer_sort_order"     = "soco"

[accessors.bool_flags]
"compilation"      = "cpil"
"gapless_playback" = "pgap"
"show_movement"    = "shwm"

[accessors.u16_ints]
"bpm"            = "tmpo"
"movement_count" = "©mvc"
"movement_index" = "©mvi"

[accessors.u32_ints]
"tv_episode" = "tves"
"tv_season"  = "tvsn"
